import { Preset } from './types';
import { DEFAULT_PARAMETERS } from './parameters';

export const PRESETS: Preset[] = [
  {
    id: 'healthy',
    label: 'Zdravý tým',
    emoji: '🟢',
    description: 'Dobře fungující tým s vyváženými procesy a technickými praktikami.',
    parameters: {
      ...DEFAULT_PARAMETERS,
      team_size: 6,
      cross_functionality: 75,
      seniority_ratio: 60,
      dedicated_team: 100,
      wip_limit: 6,
      sprint_length_days: 14,
      planning_investment: 12,
      retro_action_rate: 70,
      definition_of_done_strictness: 80,
      test_automation: 70,
      ci_cd_maturity: 75,
      code_review_thoroughness: 70,
      refactoring_investment: 10,
      tooling_investment: 10,
      inflow_rate_stories_per_sprint: 8,
      avg_story_complexity: 4,
      requirements_clarity: 80,
      scope_change_frequency: 5,
      interrupt_driven_work: 5,
      psychological_safety: 85,
      focus_time_ratio: 75,
      meeting_overhead: 10,
      stakeholder_engagement: 80,
      overtime_pressure: 0,
    },
  },
  {
    id: 'death_march',
    label: 'Death March',
    emoji: '🔴',
    description: 'Přetížený tým, vysoký technický dluh, nízká morálka. Klasická cesta k vyhoření.',
    parameters: {
      ...DEFAULT_PARAMETERS,
      team_size: 10,
      cross_functionality: 20,
      seniority_ratio: 20,
      dedicated_team: 60,
      wip_limit: 20,
      sprint_length_days: 14,
      planning_investment: 3,
      retro_action_rate: 10,
      definition_of_done_strictness: 20,
      test_automation: 5,
      ci_cd_maturity: 10,
      code_review_thoroughness: 15,
      refactoring_investment: 0,
      tooling_investment: 0,
      inflow_rate_stories_per_sprint: 25,
      avg_story_complexity: 8,
      requirements_clarity: 20,
      scope_change_frequency: 40,
      interrupt_driven_work: 35,
      psychological_safety: 15,
      focus_time_ratio: 25,
      meeting_overhead: 35,
      stakeholder_engagement: 20,
      overtime_pressure: 40,
    },
  },
  {
    id: 'startup_chaos',
    label: 'Startup Chaos',
    emoji: '🟡',
    description: 'Malý energický tým, žádné procesy, vysoké nadšení. Neschopnost škálovat bez zavedení struktury.',
    parameters: {
      ...DEFAULT_PARAMETERS,
      team_size: 3,
      cross_functionality: 90,
      seniority_ratio: 50,
      dedicated_team: 100,
      wip_limit: 15,
      sprint_length_days: 7,
      planning_investment: 3,
      retro_action_rate: 20,
      definition_of_done_strictness: 30,
      test_automation: 10,
      ci_cd_maturity: 20,
      code_review_thoroughness: 30,
      refactoring_investment: 2,
      tooling_investment: 8,
      inflow_rate_stories_per_sprint: 15,
      avg_story_complexity: 3,
      requirements_clarity: 40,
      scope_change_frequency: 35,
      interrupt_driven_work: 20,
      psychological_safety: 90,
      focus_time_ratio: 80,
      meeting_overhead: 5,
      stakeholder_engagement: 95,
      overtime_pressure: 20,
    },
  },
  {
    id: 'enterprise',
    label: 'Enterprise Waterfall-ish',
    emoji: '🔵',
    description: 'Velký tým s hodně meetingy, nízkým WIP limitem, pomalý ale stabilní.',
    parameters: {
      ...DEFAULT_PARAMETERS,
      team_size: 12,
      cross_functionality: 30,
      seniority_ratio: 55,
      dedicated_team: 50,
      wip_limit: 4,
      sprint_length_days: 28,
      planning_investment: 25,
      retro_action_rate: 30,
      definition_of_done_strictness: 90,
      test_automation: 60,
      ci_cd_maturity: 50,
      code_review_thoroughness: 80,
      refactoring_investment: 8,
      tooling_investment: 5,
      inflow_rate_stories_per_sprint: 10,
      avg_story_complexity: 8,
      requirements_clarity: 75,
      scope_change_frequency: 5,
      interrupt_driven_work: 15,
      psychological_safety: 50,
      focus_time_ratio: 40,
      meeting_overhead: 35,
      stakeholder_engagement: 60,
      overtime_pressure: 0,
    },
  },
  {
    id: 'debt_spiral',
    label: 'Tech Debt Spirála',
    emoji: '🟠',
    description: 'Ignorovaný technický dluh postupně paralyzuje celý tým. Varovný scénář.',
    parameters: {
      ...DEFAULT_PARAMETERS,
      team_size: 7,
      cross_functionality: 40,
      seniority_ratio: 30,
      dedicated_team: 90,
      wip_limit: 12,
      sprint_length_days: 14,
      planning_investment: 8,
      retro_action_rate: 25,
      definition_of_done_strictness: 30,
      test_automation: 10,
      ci_cd_maturity: 25,
      code_review_thoroughness: 20,
      refactoring_investment: 0,
      tooling_investment: 0,
      inflow_rate_stories_per_sprint: 18,
      avg_story_complexity: 6,
      requirements_clarity: 45,
      scope_change_frequency: 20,
      interrupt_driven_work: 15,
      psychological_safety: 55,
      focus_time_ratio: 45,
      meeting_overhead: 20,
      stakeholder_engagement: 55,
      overtime_pressure: 15,
    },
  },
];
